name: Test-CI/CD


on: 
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Github Action"
  run-test:
    needs: [say-hello]
    runs-on: ubuntu-latest
    steps:
      - name: checkout this repo
        uses: actions/checkout@v3

      - name: isntall dependencies
        run: sudo apt install -y build-essential python3 gcc g++ make cmake

      - name: build and test app
        run: python3 build.py
