name: DockerImage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
        - master
jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
            - name: checkout this repo
              uses: actions/checkout@v3
            
            - name: build docker
              run: docker build -t test-cicd:v0.1.0

            - name: run docker image and test source code
              run: docker run --rm test-cicd:v0.1.0

