name: DockerImage

env:
  PROJECT_NAME: ${{github.repository}}
  TEST_TAG: test
  LATEST_TAG: latest
  VERSOIN_TAG: V0.1.1

on:
  push:
    tags: [V-*]
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Build and export docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ${{env.TEST_TAG}}

      - 
        name: Test Docker image
        run: |
          docker run --rm ${{env.TEST_TAG}}

      - 
        name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{env.PROJECT_NAME}}:${{env.VERSOIN_TAG}},
            ${{ secrets.DOCKERHUB_USERNAME }}/${{env.PROJECT_NAME}}:${{env.LATEST_TAG}}
